// <auto-generated />
using System;
using FUParkingModel.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FUParkingModel.Migrations
{
    [DbContext(typeof(FUParkingDatabaseContext))]
    [Migration("20240605164444_v1.4")]
    partial class v14
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FUParkingModel.Object.Camera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<Guid>("GateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GateId");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("GateId");

                    b.ToTable("Camera", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CardNumber");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PlateNumber");

                    b.HasKey("Id");

                    b.ToTable("Card", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<Guid>("CustomerTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerTypeId");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone");

                    b.Property<string>("StatusCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusCustomer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerTypeId");

                    b.ToTable("Customer", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.CustomerType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("CustomerType", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Deposit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PackageId");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Deposit", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<Guid>("ParkingAreaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ParkingAreaId");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ParkingAreaId");

                    b.ToTable("Feedback", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Gate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<Guid>("GateTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GateTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<Guid>("ParkingAreaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ParkingAreaId");

                    b.Property<string>("StatusGate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusGate");

                    b.Property<Guid>("WPFCode")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WPFCode");

                    b.HasKey("Id");

                    b.HasIndex("GateTypeId");

                    b.HasIndex("ParkingAreaId");

                    b.ToTable("Gate", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.GateType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Descriptipn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descriptipn");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("GateType", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("CoinAmount")
                        .HasColumnType("int")
                        .HasColumnName("CoinAmount");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<int?>("EXPPackage")
                        .HasColumnType("int")
                        .HasColumnName("EXPPackage");

                    b.Property<int?>("ExtraCoin")
                        .HasColumnType("int")
                        .HasColumnName("ExtraCoin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("PackageStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PackageStatus");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.ToTable("Package", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.ParkingArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("Block")
                        .HasColumnType("int")
                        .HasColumnName("Block");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("MaxCapacity");

                    b.Property<string>("Mode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("StatusParkingArea")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusParkingArea");

                    b.HasKey("Id");

                    b.ToTable("ParkingArea", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PaymentMethodId");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SessionId");

                    b.Property<string>("StatusPayment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusPayment");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int")
                        .HasColumnName("TotalPrice");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("SessionId");

                    b.ToTable("Payment", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethod", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.PriceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<TimeOnly>("ApplyFromHour")
                        .HasColumnType("time")
                        .HasColumnName("ApplyFromHour");

                    b.Property<TimeOnly>("ApplyToHour")
                        .HasColumnType("time")
                        .HasColumnName("ApplyToHour");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<int>("MaxPrice")
                        .HasColumnType("int")
                        .HasColumnName("MaxPrice");

                    b.Property<int>("MinPrice")
                        .HasColumnType("int")
                        .HasColumnName("MinPrice");

                    b.Property<Guid>("PriceTableId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PriceTableId");

                    b.HasKey("Id");

                    b.HasIndex("PriceTableId");

                    b.ToTable("PriceItem", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.PriceTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("ApplyFromDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ApplyFromDate");

                    b.Property<DateTime>("ApplyToDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ApplyToDate");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("Priority");

                    b.Property<string>("StatusPriceTable")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusPriceTable");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VehicleTypeId");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("PriceTable", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Role", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CardId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("GateInId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GateInId");

                    b.Property<Guid>("GateOutId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GateOutId");

                    b.Property<string>("ImageInUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageInUrl");

                    b.Property<string>("ImageOutUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageOutUrl");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PlateNumber");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("TimeIn");

                    b.Property<DateTime>("TimeOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("TimeOut");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("GateInId");

                    b.HasIndex("GateOutId");

                    b.ToTable("Session", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid?>("DepositId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DepositId");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PaymentId");

                    b.Property<string>("TransactionDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TransactionDescription");

                    b.Property<string>("TransactionStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TransactionStatus");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WalletId");

                    b.HasKey("Id");

                    b.HasIndex("DepositId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transaction", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordSalt");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleId");

                    b.Property<string>("StatusUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusUser");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("BodyImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BodyImage");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("HeadImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HeadImage");

                    b.Property<string>("PlateImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PlateImage");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PlateNumber");

                    b.Property<string>("StatusVehicle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusVehicle");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VehicleTypeId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicle", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("VehicleType", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("Balance")
                        .HasColumnType("int")
                        .HasColumnName("Balance");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<DateTime?>("EXPDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EXPDate");

                    b.Property<string>("WalletStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WalletStatus");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Wallet", "dbo");
                });

            modelBuilder.Entity("FUParkingModel.Object.Camera", b =>
                {
                    b.HasOne("FUParkingModel.Object.Gate", "Gate")
                        .WithMany("Cameras")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Gate");
                });

            modelBuilder.Entity("FUParkingModel.Object.Customer", b =>
                {
                    b.HasOne("FUParkingModel.Object.CustomerType", "CustomerType")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("FUParkingModel.Object.Deposit", b =>
                {
                    b.HasOne("FUParkingModel.Object.Package", "Package")
                        .WithMany("Deposits")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("FUParkingModel.Object.Feedback", b =>
                {
                    b.HasOne("FUParkingModel.Object.Customer", "Customer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FUParkingModel.Object.ParkingArea", "ParkingArea")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ParkingAreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ParkingArea");
                });

            modelBuilder.Entity("FUParkingModel.Object.Gate", b =>
                {
                    b.HasOne("FUParkingModel.Object.GateType", "GateType")
                        .WithMany("Gates")
                        .HasForeignKey("GateTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FUParkingModel.Object.ParkingArea", "ParkingArea")
                        .WithMany("Gates")
                        .HasForeignKey("ParkingAreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GateType");

                    b.Navigation("ParkingArea");
                });

            modelBuilder.Entity("FUParkingModel.Object.Payment", b =>
                {
                    b.HasOne("FUParkingModel.Object.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FUParkingModel.Object.Session", "Session")
                        .WithMany("Payments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FUParkingModel.Object.PriceItem", b =>
                {
                    b.HasOne("FUParkingModel.Object.PriceTable", "PriceTable")
                        .WithMany("PriceItems")
                        .HasForeignKey("PriceTableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PriceTable");
                });

            modelBuilder.Entity("FUParkingModel.Object.PriceTable", b =>
                {
                    b.HasOne("FUParkingModel.Object.VehicleType", "VehicleType")
                        .WithMany("PriceTables")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("FUParkingModel.Object.Session", b =>
                {
                    b.HasOne("FUParkingModel.Object.Card", "Card")
                        .WithMany("Sessions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FUParkingModel.Object.Gate", "GateIn")
                        .WithMany("SessionGateIns")
                        .HasForeignKey("GateInId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FUParkingModel.Object.Gate", "GateOut")
                        .WithMany("SessionGateOuts")
                        .HasForeignKey("GateOutId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("GateIn");

                    b.Navigation("GateOut");
                });

            modelBuilder.Entity("FUParkingModel.Object.Transaction", b =>
                {
                    b.HasOne("FUParkingModel.Object.Deposit", "Deposit")
                        .WithMany("Transactions")
                        .HasForeignKey("DepositId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FUParkingModel.Object.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FUParkingModel.Object.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Deposit");

                    b.Navigation("Payment");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FUParkingModel.Object.User", b =>
                {
                    b.HasOne("FUParkingModel.Object.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FUParkingModel.Object.Vehicle", b =>
                {
                    b.HasOne("FUParkingModel.Object.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FUParkingModel.Object.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("FUParkingModel.Object.Wallet", b =>
                {
                    b.HasOne("FUParkingModel.Object.Customer", "Customer")
                        .WithMany("Wallets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FUParkingModel.Object.Card", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("FUParkingModel.Object.Customer", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Vehicles");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("FUParkingModel.Object.CustomerType", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("FUParkingModel.Object.Deposit", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FUParkingModel.Object.Gate", b =>
                {
                    b.Navigation("Cameras");

                    b.Navigation("SessionGateIns");

                    b.Navigation("SessionGateOuts");
                });

            modelBuilder.Entity("FUParkingModel.Object.GateType", b =>
                {
                    b.Navigation("Gates");
                });

            modelBuilder.Entity("FUParkingModel.Object.Package", b =>
                {
                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("FUParkingModel.Object.ParkingArea", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Gates");
                });

            modelBuilder.Entity("FUParkingModel.Object.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FUParkingModel.Object.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FUParkingModel.Object.PriceTable", b =>
                {
                    b.Navigation("PriceItems");
                });

            modelBuilder.Entity("FUParkingModel.Object.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FUParkingModel.Object.Session", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FUParkingModel.Object.VehicleType", b =>
                {
                    b.Navigation("PriceTables");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("FUParkingModel.Object.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
