// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.VehicleService.#ctor(FUParkingRepository.Interface.IVehicleRepository,FUParkingService.Interface.IHelpperService,FUParkingRepository.Interface.IUserRepository,FUParkingRepository.Interface.ICustomerRepository,FUParkingService.Interface.IMinioService)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.UserService.#ctor(FUParkingRepository.Interface.IUserRepository,FUParkingRepository.Interface.IRoleRepository,FUParkingService.Interface.IHelpperService)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.TransactionService.#ctor(FUParkingRepository.Interface.ITransactionRepository,FUParkingRepository.Interface.IUserRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.PriceSevice.#ctor(FUParkingRepository.Interface.IPriceRepository,FUParkingRepository.Interface.IVehicleRepository,FUParkingService.Interface.IHelpperService,FUParkingRepository.Interface.IUserRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.PaymentService.#ctor(FUParkingRepository.Interface.IPaymentRepository,FUParkingService.Interface.IHelpperService,FUParkingRepository.Interface.IUserRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.ParkingAreaService.#ctor(FUParkingRepository.Interface.IParkingAreaRepository,FUParkingService.Interface.IHelpperService,FUParkingRepository.Interface.IUserRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.PackageService.#ctor(FUParkingRepository.Interface.IPackageRepository,FUParkingRepository.Interface.IUserRepository,FUParkingService.Interface.IHelpperService)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.InitializeDataService.#ctor(FUParkingService.Interface.IHelpperService,FUParkingRepository.Interface.IGateRepository,FUParkingRepository.Interface.IVehicleRepository,FUParkingRepository.Interface.IRoleRepository,FUParkingRepository.Interface.IUserRepository,FUParkingRepository.Interface.ICustomerRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.HelpperService.#ctor(Microsoft.Extensions.Configuration.IConfiguration,Microsoft.AspNetCore.Http.IHttpContextAccessor)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.FeedbackService.#ctor(FUParkingRepository.Interface.IFeedbackRepository,FUParkingRepository.Interface.ICustomerRepository,FUParkingRepository.Interface.IParkingAreaRepository,FUParkingRepository.Interface.IUserRepository,FUParkingService.Interface.IHelpperService)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.CardService.#ctor(FUParkingRepository.Interface.ICardRepository,FUParkingService.Interface.IHelpperService,FUParkingRepository.Interface.IUserRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.AuthService.#ctor(FUParkingRepository.Interface.ICustomerRepository,Microsoft.Extensions.Configuration.IConfiguration,FUParkingRepository.Interface.IWalletRepository,FUParkingRepository.Interface.IUserRepository,FUParkingService.Interface.IHelpperService)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.SessionService.#ctor(FUParkingRepository.Interface.ISessionRepository,FUParkingService.Interface.IHelpperService,FUParkingRepository.Interface.IUserRepository,FUParkingRepository.Interface.ICardRepository,FUParkingRepository.Interface.IGateRepository,FUParkingService.Interface.IMinioService,FUParkingRepository.Interface.IParkingAreaRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.WalletService.#ctor(FUParkingRepository.Interface.IWalletRepository,FUParkingRepository.Interface.ICustomerRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.CustomerService.#ctor(FUParkingRepository.Interface.ICustomerRepository,FUParkingRepository.Interface.IUserRepository,FUParkingService.Interface.IHelpperService)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.GateService.#ctor(FUParkingRepository.Interface.IUserRepository,FUParkingService.Interface.IHelpperService,FUParkingRepository.Interface.IGateRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:FUParkingService.ZaloService.#ctor(FUParkingService.Interface.ICustomerService,FUParkingService.Interface.IHelpperService,FUParkingRepository.Interface.IPackageRepository,Microsoft.Extensions.Configuration.IConfiguration,FUParkingRepository.Interface.IWalletRepository,FUParkingRepository.Interface.IPaymentRepository,FUParkingRepository.Interface.IDepositRepository,FUParkingRepository.Interface.ITransactionRepository,System.Net.Http.IHttpClientFactory)")]
